import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import { Toaster } from 'sonner'

import './globals.scss'

const notoSans = Noto_Sans({
	variable: '--font-geist-sans',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Focusphere',
	description: 'Generated by create next app',
	verification: {
		google: 'ip_ipW9nCeVSX12gwMPI0UdkdmX7u66iVJvL5Emj8PY',
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${notoSans.variable}`}>
				{children} <Toaster position='bottom-right' richColors />
			</body>
		</html>
	)
}
