import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import { Toaster } from 'sonner'

import Script from 'next/script'
import './globals.scss'

const notoSans = Noto_Sans({
	variable: '--font-geist-sans',
	subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
	title: 'Focusphere',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<Script defer src='https://cloud.umami.is/script.js' data-website-id='e247f637-575b-4bd3-b79c-c573760b74c9' />
			</head>
			<body className={`${notoSans.variable}`}>
				{children} <Toaster position='bottom-right' richColors />
			</body>
		</html>
	)
}
